### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by guillim** [huggingface/node-question-answering#1]
Hello,

First thanks for your work, looks great. Wish I could try it but :

I am stuck trying your package on the first step :
```bash
npx question-answering download
```

I have this issue raising:
> node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.4.1/index-v0.4.1-node-v57-darwin-x64-unknown.tar.gz

It could be a problem on my side like my ISP blocking, but I doubt it. And I am not using any proxies. Am I the only one experiencing this?

**Comment by Pierrci** [comment]
Hi, your problem is related to the version of Node.js you're using. The package is only compatible with versions 10.x, 12.x and 13.x because of the [`tokenizers`](https://github.com/huggingface/tokenizers) library used internally for tokenization.

Let me know if it works with one of those versions!

**Comment by guillim** [comment]
Tks @Pierrci  it works fine now !

for those with same issue :
```bash
sudo n 13
```
Should do (install [n](https://www.npmjs.com/package/n) if you haven't or follow [another technique](https://bytearcher.com/articles/ways-to-get-the-latest-node.js-version-on-a-mac/))

**Comment by seppestaes** [comment]
Installing it locally works fine (node 12.21.0). Installing it on github whilst specifying the same node version throws this error:

`stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v83-linux-x64-glibc.tar.gz`
